# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled_fw.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Key(object):
    def setupUi(self, Key):
        Key.setObjectName("Key")
        Key.resize(476, 339)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Key.sizePolicy().hasHeightForWidth())
        Key.setSizePolicy(sizePolicy)
        Key.setMinimumSize(QtCore.QSize(476, 339))
        Key.setMaximumSize(QtCore.QSize(476, 339))
        Key.setStyleSheet("background-color: rgb(0, 0, 0)")
        self.gridLayout = QtWidgets.QGridLayout(Key)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_3 = QtWidgets.QPushButton(Key)
        self.pushButton_3.setMinimumSize(QtCore.QSize(441, 61))
        self.pushButton_3.setMaximumSize(QtCore.QSize(431, 61))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: \"Yu Gothic UI Semibold\";\n"
"border-radius: 16px;\n"
"font-size: 12pt;")
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 0, 0, 1, 2)
        self.pushButton = QtWidgets.QPushButton(Key)
        self.pushButton.setMinimumSize(QtCore.QSize(251, 61))
        self.pushButton.setMaximumSize(QtCore.QSize(251, 61))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: \"Yu Gothic UI Semibold\";\n"
"border-radius: 16px;\n"
"font-size: 12pt;")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 1, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(Key)
        self.pushButton_2.setMinimumSize(QtCore.QSize(171, 61))
        self.pushButton_2.setMaximumSize(QtCore.QSize(171, 61))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: \"Yu Gothic UI Semibold\";\n"
"border-radius: 16px;\n"
"font-size: 12pt;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 1, 1, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(Key)
        self.pushButton_4.setMinimumSize(QtCore.QSize(251, 61))
        self.pushButton_4.setMaximumSize(QtCore.QSize(251, 61))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: \"Yu Gothic UI Semibold\";\n"
"border-radius: 16px;\n"
"font-size: 12pt;")
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 2, 0, 1, 1)
        self.frame = QtWidgets.QFrame(Key)
        self.frame.setMinimumSize(QtCore.QSize(171, 61))
        self.frame.setMaximumSize(QtCore.QSize(171, 61))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: \"Yu Gothic UI Semibold\";\n"
"border-radius: 16px;\n"
"font-size: 12pt;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setStyleSheet("font: \"Yu Gothic UI Semibold\";\n"
"font-size: 12pt;")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_2.addWidget(self.lineEdit, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 2, 1, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(Key)
        self.pushButton_5.setMinimumSize(QtCore.QSize(441, 61))
        self.pushButton_5.setMaximumSize(QtCore.QSize(441, 61))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"    font: 63 12pt \"Yu Gothic UI Semibold\";\n"
"    border-radius: 16px\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(76, 76, 76);\n"
"    border-radius: 16px\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(116, 116, 116);\n"
"    border-radius: 16px\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 3, 0, 1, 2)

        self.retranslateUi(Key)
        QtCore.QMetaObject.connectSlotsByName(Key)

    def retranslateUi(self, Key):
        _translate = QtCore.QCoreApplication.translate
        Key.setWindowTitle(_translate("Key", "Key"))
        self.pushButton_3.setText(_translate("Key", "ЭТО ОКНО ПОЯВЛЯЕТСЯ ТОЛЬКО В ПЕРВЫЙ РАЗ"))
        self.pushButton.setText(_translate("Key", "1)Зарегистрируйтесь на сайте:"))
        self.pushButton_2.setText(_translate("Key", "https://xtunnel.ru/"))
        self.pushButton_4.setText(_translate("Key", "2)Введите полученный ключ:"))
        self.pushButton_5.setText(_translate("Key", "Запустить сайт"))
